apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: snsgateway
  labels:
    k8s-app: snsgateway-service
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: snsgateway-service
  template:
    metadata:
      labels:
        k8s-app: snsgateway-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: snsgateway
        image: betyar/snsgateway:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: my-env
 
---
apiVersion: v1
kind: Service
metadata:
  name: snsgateway
spec:
  selector:
    app: snsgateway
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
